### ISSUE TITLE
Some question about simulation

### ISSUE THREAD

**Issue by Tom-900** [kunwang34/PhyloVelo#11]
Thank you for developing this package! I have a question after reading the paper on nature biotech. In section "Simulating cell division history and mutation-based phylogeny", I noticed that there is a discription like:

_After obtaining the cell mutational information, we used three different algorithms to reconstruct the phylogenetic tree, respectively, namely Maximum Likelihood (using IQ-TREE 2 (ref. 76), Neighbor-Joining (using the R package ape 5.6-2 (ref. 77) and Maximum Parsimony (using the R package phangorn 2.11.1)._

I wonder why we should reconstruct tree like this, since as far as I know this step needs DNA sequence. And from the _reconstruct_ function in file _sim_utils.py_ it seems that it is used to do downsampling.

I'll appreciate it if you could kindly help me figure it out.

**Comment by kunwang34** [comment]
Hi, thank you for your interest in our package and paper. The purpose of
the reconstruct function in sim_utils.py is to retrieve the original
phylogenetic tree, based on the simulated cell lineage data that is
produced by our package. The MP, ML and NJ algorithms are applied to
evaluate the performance of PhyloVelo in various tree reconstruction
scenarios, and the input DNA-seq data is also simulated by our package.
This allows us to compare the accuracy of PhyloVelo with different tree
reconstruction algorithms on the same simulated data.

GE Muyang ***@***.***> 于2023年9月13日周三 00:15写道：

**Comment by Tom-900** [comment]
Thank you very much for your answer!
