### ISSUE TITLE
How can I prepare the data to successfully run the HEK293T.ipynb code?

### ISSUE THREAD

**Issue by JangYeoRyeong** [kunwang34/PhyloVelo#13]
Hi,
Thank you very much for developing this great tool!!
I want to follow your codes by using the same PRJNA757179 data.
I'm trying to run `notebooks/HEK293T.ipynb` but I have a question about the data you used.

I created a loom file using the SRR18280236 and SRR18280237 data and created tree using the `DNATypewriter_SingleCellLineage_Rscript.R` script, which was avaliable along with the `Supplementary_File_2_DataTableMOI19.csv` data on the DNATickerTape GitHub page.
However, when I use this data to run the `HEK293T.ipynb`, I am unable to get any selected_cells.

Could you please explain how I can prepare the data (such as adata, datatable, tree, cells) to successfully run the `HEK293T.ipynb` code?

I would be very grateful for your help.

**Comment by kunwang34** [comment]
Hello @JangYeoRyeong ,
It looks like there might be an inconsistency in the cell names between  `Supplementary_File_2_DataTableMOI19.csv` and the loom file. In the CSV file, the cell names are formatted like `AAGCCATAGCGCCTAC-1`, while in the loom file, they appear as `SRR18280236:AAGCCATAGCGCCTACx`.
To resolve this, you should remove any extra suffixes or prefixes and keep only the barcodes `AAGCCATAGCGCCTAC`. This will ensure consistency across your data files.

**Comment by JangYeoRyeong** [comment]
Thank you so much, @kunwang34.
I solved the problem.
I really appreciate your help!
Again, thank you so much.
