### ISSUE TITLE
 "sd_early" not defined in the section "KPtracer-mouse tumor evolution" of the accompanied docs

### ISSUE THREAD

**Issue by zebrafishCC** [kunwang34/PhyloVelo#3]
Dear Dr. Wang
     It's great to find out PhyloVelo outperforms scVelocity! However, an error was raised when I was following the function of cell34 in the accompanied docs (https://phylovelo.readthedocs.io/en/latest/notebook/KPTracer-3726-t1.html), and the error message is shown below:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_66870/2961152088.py in <module>
----> 1 sd_early.count = sd_early.count.loc[sel_cells]
      2 sd_early.x_normed = sd_early.x_normed.loc[sel_cells]
      3 sd_early.Xdr = sd_early.Xdr.loc[sel_cells]
NameError: name 'sd_early' is not defined

Could you please show the definition of "sd_early"?

Best regards,

Cheng

**Comment by kunwang34** [comment]
Hi Cheng,

Very sorry for the bug. You can follow this notebook first https://github.com/kunwang34/PhyloVelo/blob/main/notebooks/KPTracer-3726-t1.ipynb and I will update the website soon

**Comment by zebrafishCC** [comment]
The new link works, thanks!
