### ISSUE TITLE
C.elegans_demo; pseudoembryo0_count.csv access 

### ISSUE THREAD

**Issue by AvitalRodov** [kunwang34/PhyloVelo#8]
Hi!
Thank you very much for this ameizing tool! 
Im trying to run the example provided in C.elegans_demo.ipynb but I couldn’t find the pseudoembryo0_count.csv file. 
I guessed it was reproduced from randomly choosing one represent of a node from 'GSE126954_gene_by_cell_count_matrix.txt'. If so it would be great if you can share the code for this! 

Can you maybe assist me with getting pseudoembryo0_count.csv? 
Thank you!
Avital

**Comment by kunwang34** [comment]
Hi Avital,

Thank you for your interest in our PhyloVelo tool. We have updated the C.elegans demo dataset at https://github.com/kunwang34/PhyloVelo/tree/master/demo/datasets/Celegans.

We hope you enjoy using our tool and find it useful for your research. If you have any questions or feedback, please don’t hesitate to reply.

Best, Kun

**Comment by AvitalRodov** [comment]
Thank you very much!

**Comment by AvitalRodov** [comment]
Thank you very much!
