### ISSUE TITLE
Whether this tool can be used for one sample TCR data?

### ISSUE THREAD

**Issue by MugenQin** [kunwang34/PhyloVelo#9]
Thanks for this good tool! I wanna analyse my data for one sample, but while I run `dyn.pd.state_graph`, I got this error:
`ValueError: need at least one array to concatenate`
Could you give me some ideas for this error?

**Comment by kunwang34** [comment]
Hi Mugen,

To help me diagnose the problem, could you please share your code and the full error output you got when you ran dyn.pd.state_graph? You can paste it in a code block.

I will try to figure out what’s wrong and get back to you as soon as possible.

**Comment by MugenQin** [comment]
Hi kun,

I fellow the tutorial on the "Apply PhyloVelo to clonal lineage tracing data - TCR" page, I run successfully while I had more than one sample to run. But I got this error while I just run one sample. I made it as reference and then run the pipeline like I have more than one sample.

**Comment by MugenQin** [comment]
> Hi Mugen,
> 
> To help me diagnose the problem, could you please share your code and the full error output you got when you ran dyn.pd.state_graph? You can paste it in a code block.
> 
> I will try to figure out what’s wrong and get back to you as soon as possible.

Hi kun,

I fellow the tutorial on the "Apply PhyloVelo to clonal lineage tracing data - TCR" page, I run successfully while I had more than one sample to run. But I got this error while I just run one sample. I made it as reference and then run the pipeline like I have more than one sample.

**Comment by kunwang34** [comment]
One sample data is suitable for PhyloVelo analysis, but the error you reported is related to the dynamo tool. To diagnose the problem, I need the full error output that you got when you ran the tool. Please copy and paste the error message here, or attach a screenshot of it. This will help me to find the source of the issue and provide a solution.

**Comment by MugenQin** [comment]
> One sample data is suitable for PhyloVelo analysis, but the error you reported is related to the dynamo tool. To diagnose the problem, I need the full error output that you got when you ran the tool. Please copy and paste the error message here, or attach a screenshot of it. This will help me to find the source of the issue and provide a solution.

Sorry for the delayed reply, I had solved that problem.
